TypeError
Python 3.9.11: F:\shimo-2.0\.venv\Scripts\python.exe
Sun Feb 18 16:51:00 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 F:\shimo-2.0\sm.py in <module>
  530     apply_stylesheet(app, theme='light_blue_500.xml', invert_secondary=True)
  531     # app.setStyleSheet(QssStyle1)
  532     ex = DetailUI()
  533     ex.show()
  534     sys.exit(app.exec_())
ex undefined
DetailUI = <class '__main__.DetailUI'>

 F:\shimo-2.0\sm.py in __init__(self=<__main__.DetailUI object>)
   34         self.debug_thread = None
   35         self.analy_thread = None
   36         self.setupUi(self)
   37         self.example = ExampleBox()
   38         self.example.setMinimumSize(QtCore.QSize(0, 25))
self = <__main__.DetailUI object>
self.setupUi = <bound method Ui_MainWindow.setupUi of <__main__.DetailUI object>>

 F:\shimo-2.0\common\ui\MainWindow.py in setupUi(self=<__main__.DetailUI object>, MainWindow=<__main__.DetailUI object>)
   19         MainWindow.setStyleSheet("background:rgb(186,211,218);border:none;\n"
   20 "font: 57 10pt \"MiSans Medium\";")
   21         self.centralwidget = QtWidgets.QWidget(MainWindow)
   22         self.centralwidget.setObjectName("centralwidget")
   23         self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
self = <__main__.DetailUI object>
self.centralwidget undefined
global QtWidgets = <module 'PySide6.QtWidgets' from 'F:\\shimo-2.0\\.venv\\lib\\site-packages\\PySide6\\QtWidgets.pyd'>
QtWidgets.QWidget = <class 'PySide6.QtWidgets.QWidget'>
MainWindow = <__main__.DetailUI object>
TypeError: 'PySide6.QtWidgets.QWidget.__init__' called with wrong argument types:
  PySide6.QtWidgets.QWidget.__init__(DetailUI)
Supported signatures:
  PySide6.QtWidgets.QWidget.__init__(Optional[PySide6.QtWidgets.QWidget] = None, PySide6.QtCore.Qt.WindowType = Default(Qt.WindowFlags))
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'PySide6.QtWidgets.QWidget.__init__' called with...6.QtCore.Qt.WindowType = Default(Qt.WindowFlags))",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "F:\shimo-2.0\sm.py", line 532, in <module>
    ex = DetailUI()
  File "F:\shimo-2.0\sm.py", line 36, in __init__
    self.setupUi(self)
  File "F:\shimo-2.0\common\ui\MainWindow.py", line 21, in setupUi
    self.centralwidget = QtWidgets.QWidget(MainWindow)
TypeError: 'PySide6.QtWidgets.QWidget.__init__' called with wrong argument types:
  PySide6.QtWidgets.QWidget.__init__(DetailUI)
Supported signatures:
  PySide6.QtWidgets.QWidget.__init__(Optional[PySide6.QtWidgets.QWidget] = None, PySide6.QtCore.Qt.WindowType = Default(Qt.WindowFlags))

